/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"

//==============================================================================
/**
*/
class Mu45effectAudioProcessorEditor  : public AudioProcessorEditor,
                                        public Slider::Listener,
                                        public Timer,
                                        public ComboBoxListener
{
public:
    Mu45effectAudioProcessorEditor (Mu45effectAudioProcessor&);
    ~Mu45effectAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;
    void sliderValueChanged(Slider*) override;
    void timerCallback() override;
    void comboBoxChanged (ComboBox* comboBoxThatHasChanged) override;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    Mu45effectAudioProcessor& processor;
    
    ScopedPointer<Slider> Rate;
    ScopedPointer<Slider> Phase;
    ScopedPointer<Slider> WetDry;
    ScopedPointer<ComboBox> Waveform;
    ScopedPointer<Label> Rate2;
    ScopedPointer<Label> Phase2;
    ScopedPointer<Label> label;
    ScopedPointer<Label> Waveform2;
    ScopedPointer<ComboBox> PreFilt;
    ScopedPointer<ComboBox> PostFilt;
    ScopedPointer<Label> PreFilter;
    ScopedPointer<Label> PostFilter;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (Mu45effectAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
